INSERT INTO teams (id, city, team_name)
VALUES (1, "Los Angeles", "Dodgers"),
       (2, "Cincinnati", "Reds"),
       (3, "Toronto", "Blue Jays"),
       (4, "Pittsburgh", "Pirates"),
       (5, "Kansas City", "Royals"),
       (9, "Chicago", "Cubs"),
       (10, "Cleveland", "Guardians"),
       (11, "Tampa Bay", "Rays"),
       (12, "Philadelphia", "Phillies"),
       (13, "Seattle", "Mariners"),
       (14, "Arizona", "Diamondbacks"),
       (15, "San Francisco", "Giants"),
       (16, "Chicago", "White Sox"),
       (17, "Detroit", "Tigers"),
       (18, "New York", "Mets"),
       (19, "Baltimore", "Orioles"),
       (20, "Minnesota", "Twins"),
       (21, "Los Angeles", "Angels"),
       (22, "Miami", "Marlins"),
       (23, "Colorado", "Rockies"),
       (24, "Oakland", "Athletics"),
       (25, "Boston", "Red Sox"),
       (26, "Atlanta", "Braves"),
       (28, "Texas", "Rangers"),
       (29, "New York", "Yankees"),
       (30, "Houston", "Astros"),
       (31, "St. Louis", "Cardinals"),
       (32, "Milwaukee", "Brewers"),
       (33, "San Diego ", "Padres"),
       (35, "Washington", "Nationals");

INSERT INTO positions (id, position)
VALUES (1, "IF"),
       (2, "OF"),
       (3, "P"),
       (4, "C"),
       (5, "H");